### ISSUE TITLE
Ipad not correctly detected

### ISSUE THREAD

**Issue by omida86** [laskoviymishka/MvcDeviceDetector#1]
Ipad useragent contains mobile, so the mobile view is returned instead of tablet view as per AgentResolver.cs:

```
            if (agent != null && TabletUserAgentKeywords.Any(keyword => agent.Contains(keyword) && !agent.Contains("mobile")))
            {
                return _deviceFactory.Tablet();
            } 

```

I solved it by making my own resolver for now: 
`
            services.AddTransient<IDeviceResolver, CustomAgentResolver>();`

And in the CustomAgentResolver:

```
            if (agent != null && TabletUserAgentKeywords.Any(keyword => agent.Contains(keyword) && !agent.Contains("mobile")))
            {
                return _deviceFactory.Tablet();
            } 
            
            if (agent != null && agent.Contains("ipad"))
            {
                return _deviceFactory.Tablet();
            }
```

**Comment by laskoviymishka** [comment]
There is also other option.
`DeviceOptions` class contains ability to extends list of known user agents.

So on startup of you app you could add options:

`services.AddDeviceDetector(device => { device.TabletUserAgentKeywords.Add("YOUR KEYWORD"); })`

Default agent resolver will firstly look for tablet (as not so common case) so it will find you key word and return proper tablet device.

But this is require fix for source code

**Comment by omida86** [comment]
Commit 4fe57a7:
This will not work correctly on Android tablets, since android detection need this check. Or else it will return Android mobile devices as tablet.
