### ISSUE TITLE
Add preference switcher mechanism

### ISSUE THREAD

**Issue by mrnams** [laskoviymishka/MvcDeviceDetector#5]
I have included MvcDeviceDetector package in my website https://mrnams.com  via .

Install-Package MvcDeviceDetector -Pre

Can you please share me code to set preference in     public class Startup()

I mean I want to set preference to use mobile views always, even though browsed from desktop.

I need this ti test mobile version on desktop and desktop version on mobile,after successfully testing.

I shall just use
services.AddDeviceDetector();

I could not understand to use
You could also add preference switcher mechanism, to enable switch:

services.AddDeviceSwitcher<UrlSwitcher>(switcherOptions => { }, deviceOptions => { });

Please share exact code to use.

**Comment by laskoviymishka** [comment]
Hello,

I provide an running example in https://github.com/laskoviymishka/MvcDeviceDetector/blob/master/sample/MvcSandbox/Startup.cs#L31

You can look in this sample.
